version: '3.8'

services:
  # PostgreSQL с TimescaleDB для разработки
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: trading-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: trading_bot
      POSTGRES_PASSWORD: robocop
      POSTGRES_DB: trading_bot
    ports:
      - "5432:5432"
    volumes:
      # Сохранение данных между перезапусками
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin для управления базой данных (опционально)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trading-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@trading.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
